doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            AppEntity:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/entity'
                prefix: App\Infrastructure\ORM\Entity
                alias: AppEntity
            AppValueObject:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/value_object'
                prefix: App\Infrastructure\ORM\ValueObject
                alias: AppValueObject
