services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /app
    ports:
      - '${APP_PORT:-8080}:${APP_PORT:-8080}'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - ./:/app
    networks:
      - picpay_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:${APP_PORT:-8080}/up || exit 1" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    #    mem_limit: 512m
    #    cpus: 1
    entrypoint:
      - sh
      - -c
      - |
        php artisan serve --host=0.0.0.0 --port=${APP_PORT:-8080} &
        npm run dev -- --host --port ${VITE_PORT:-5173} &
        wait

networks:
  picpay_network:
    driver: bridge
