# Generated by Django 5.0.6 on 2024-06-21 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizacao', models.CharField(choices=[('transicao', 'Transição')], default='transicao', max_length=50)),
                ('autorizado', models.BooleanField(default=False)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apipicpay.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apipicpay.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='ChavePix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('chave_aleatoria', models.CharField(max_length=50, unique=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apipicpay.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAutorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizado', models.BooleanField(default=False)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apipicpay.tipousuario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apipicpay.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ativo', models.BooleanField()),
                ('chave_pix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apipicpay.chavepix')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apipicpay.usuario')),
                ('autorizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apipicpay.usuarioautorizacao')),
            ],
        ),
    ]
