# Generated by Django 5.0.6 on 2024-06-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipicpay', '0002_autorizacao_usuario_fisico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldouser',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
