# Generated by Django 5.0.6 on 2024-06-13 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipicpay', '0003_alter_saldouser_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorizacao',
            old_name='usuario_fisico',
            new_name='autorizado',
        ),
        migrations.RemoveField(
            model_name='autorizacao',
            name='autorizacao',
        ),
        migrations.RemoveField(
            model_name='autorizacao',
            name='usuario_juridico',
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='tipo_autorizacao',
            field=models.CharField(choices=[('transicao', 'Transição')], default='transicao', max_length=50),
        ),
        migrations.AlterField(
            model_name='autorizacao',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apipicpay.tipousuario'),
        ),
    ]
