# Generated by Django 5.0.6 on 2024-06-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipicpay', '0004_rename_usuario_fisico_autorizacao_autorizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldouser',
            name='autorizacao',
        ),
        migrations.AddField(
            model_name='saldouser',
            name='tipo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apipicpay.autorizacao'),
        ),
    ]
