# Generated by Django 5.0.6 on 2024-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipicpay', '0005_remove_saldouser_autorizacao_saldouser_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldouser',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
