# Generated by Django 5.0.6 on 2024-06-13 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipicpay', '0006_alter_saldouser_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorizacao',
            old_name='tipo_autorizacao',
            new_name='autorizacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuarioautorizacao',
            name='autorizacao',
        ),
        migrations.AddField(
            model_name='usuarioautorizacao',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apipicpay.tipousuario'),
        ),
        migrations.DeleteModel(
            name='SaldoUser',
        ),
    ]
