# Generated by Django 5.0.6 on 2024-06-17 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipicpay', '0008_alter_usuarioautorizacao_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativo', models.BooleanField()),
                ('autorizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apipicpay.usuarioautorizacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apipicpay.usuario')),
            ],
        ),
    ]
