# Generated by Django 5.0.6 on 2024-06-17 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipicpay', '0009_saldouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChavePix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('chave_aleatoria', models.CharField(max_length=50, unique=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apipicpay.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='saldouser',
            name='chave_pix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apipicpay.chavepix'),
        ),
    ]
