# Generated by Django 5.0.6 on 2024-06-17 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipicpay', '0010_chavepix_saldouser_chave_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldouser',
            name='chave_pix',
            field=models.ForeignKey(blank=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apipicpay.chavepix'),
        ),
    ]
