spring.application.name=picpay-challenge
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway settings
flyway.enabled=true
flyway.locations=classpath:db/migration
flyway.baseline-on-migrate=true
