spring.application.name=challenge
spring.datasource.url=jdbc:postgresql://localhost:5432/picpay-challenge
spring.datasource.username=postgres
spring.datasource.password=localhostroot
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG
