###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.4"
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.30.0.0/16
services:

    memcached:
      image: memcached
      container_name: memcached-pp
      restart: always
      networks:
        static-network:
          ipv4_address: 172.30.128.5

    mysql:
      image: mysql
      container_name: mysql-pp
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      volumes:
        - ./mysql-data:/var/lib/mysql/
      extra_hosts:
        - "web-pp:172.30.128.2"
      networks:
        static-network:
          ipv4_address: 172.30.128.6
      environment:
        MYSQL_ROOT_PASSWORD: root
      security_opt:
        - seccomp:unconfined

    webserver:
      image: nginx
      container_name: web-pp
      working_dir: /pp
      volumes:
        - ../../pp:/pp
        - ./phpdocker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./phpdocker/nginx/pp.conf:/etc/nginx/sites-enabled/pp.conf
      extra_hosts:
        - "php7-pp:172.30.128.4"
      ports:
       - "8080:80"
      networks:
        static-network:
          ipv4_address: 172.30.128.2

    php7:
      build: phpdocker/php74-fpm
      container_name: php7-pp
      working_dir: /pp
      volumes:
        - ../../pp:/pp
      extra_hosts:
        - "web-pp:172.30.128.2"
        - "mysql:172.30.128.6"
      networks:
        static-network:
          ipv4_address: 172.30.128.4







