version: "3.8"
services:
  web_core:
    container_name: ${WEB_CORE_CONTAINER_NAME}
    build:
      context: ${WEB_HOST_BUILDER_PATH}
      dockerfile: ${DOCKERFILE}
    ports:
      - "${WEB_CORE_HOST_HTTP_PORT}:${WEB_CONTAINER_HTTP_PORT}"
    volumes:
      - ${APPLICATION_CORE_HOST_PATH}:${APPLICATION_CORE_CONTAINER_PATH}
      - ${WEB_CORE_APACHE_HOST_LOG}:${APACHE_CONTAINER_LOG}
      - ${WEB_CORE_APACHE_HOST_SITES_AVAILABLE}:${APACHE_CONTAINER_SITES_AVAILABLE}
      - ${WEB_CORE_PHP_HOST_CONF}:${PHP_CONTAINER_CONF}
  web_wallet:
    container_name: ${WEB_WALLET_CONTAINER_NAME}
    build:
      context: ${WEB_HOST_BUILDER_PATH}
      dockerfile: ${DOCKERFILE}
    ports:
      - "${WEB_WALLET_HOST_HTTP_PORT}:${WEB_CONTAINER_HTTP_PORT}"
    volumes:
      - ${APPLICATION_WALLET_HOST_PATH}:${APPLICATION_WALLET_CONTAINER_PATH}
      - ${WEB_WALLET_APACHE_HOST_LOG}:${APACHE_CONTAINER_LOG}
      - ${WEB_WALLET_APACHE_HOST_SITES_AVAILABLE}:${APACHE_CONTAINER_SITES_AVAILABLE}
      - ${WEB_WALLET_PHP_HOST_CONF}:${PHP_CONTAINER_CONF}
  mongo_core:
    container_name: ${MONGO_CORE_CONTAINER_NAME}
    build:
      context: ${MONGO_HOST_BUILDER_PATH}
      dockerfile: ${DOCKERFILE}
    restart: ${ALWAYS}
    ports:
      - ${MONGO_CORE_HOST_HTTP_PORT}:${MONGO_CONTAINER_HTTP_PORT}
    networks:
      - ${MONGO_CORE_NETWORK}
    volumes:
      - ${MONGO_CORE_EXTERNAL_VOLUME_DATA}:${MONGO_CONTAINER_DATA}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  mongo_wallet:
    container_name: ${MONGO_WALLET_CONTAINER_NAME}
    build:
      context: ${MONGO_HOST_BUILDER_PATH}
      dockerfile: ${DOCKERFILE}
    restart: ${ALWAYS}
    ports:
      - ${MONGO_WALLET_HOST_HTTP_PORT}:${MONGO_CONTAINER_HTTP_PORT}
    networks:
      - ${MONGO_WALLET_NETWORK}
    volumes:
      - ${MONGO_WALLET_EXTERNAL_VOLUME_DATA}:${MONGO_CONTAINER_DATA}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  mongo_express_core:
    container_name: ${MONGO_EXPRESS_CORE_CONTAINER_NAME}
    build:
      context: ${MONGO_EXPRESS_HOST_BUILDER_PATH}
      dockerfile: ${DOCKERFILE}
    restart: ${ALWAYS}
    ports:
      - ${MONGO_EXPRESS_CORE_HOST_HTTP_PORT}:${MONGO_EXPRESS_CONTAINER_HTTP_PORT}
    networks:
      - ${MONGO_CORE_NETWORK}
    links:
      - ${MONGO_CORE_LINK_SERVICE}
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_CORE_CONTAINER_NAME}
      - ME_CONFIG_MONGODB_PORT=${MONGO_CONTAINER_HTTP_PORT}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  mongo_express_wallet:
    container_name: ${MONGO_EXPRESS_WALLET_CONTAINER_NAME}
    build:
      context: ${MONGO_EXPRESS_HOST_BUILDER_PATH}
      dockerfile: ${DOCKERFILE}
    restart: ${ALWAYS}
    ports:
      - ${MONGO_EXPRESS_WALLET_HOST_HTTP_PORT}:${MONGO_EXPRESS_CONTAINER_HTTP_PORT}
    networks:
      - ${MONGO_WALLET_NETWORK}
    links:
      - ${MONGO_WALLET_LINK_SERVICE}
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_WALLET_CONTAINER_NAME}
      - ME_CONFIG_MONGODB_PORT=${MONGO_CONTAINER_HTTP_PORT}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  rabbitmq_core:
    container_name: ${RABBITMQ_CORE_CONTAINER_NAME}
    build:
      context: ${RABBITMQ_HOST_BUILDER_PATH}
      dockerfile: ${DOCKERFILE}
    restart: ${ALWAYS}
    ports:
      - ${RABBITMQ_CORE_HOST_HTTP_PORT}:${RABBITMQ_CONTAINER_HTTP_PORT}
      - ${RABBITMQ_CORE_MANAGEMENT_HOST_HTTP_PORT}:${RABBITMQ_MANAGEMENT_CONTAINER_HTTP_PORT}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ${RABBITMQ_CORE_HOST_ETC}:${RABBITMQ_CONTAINER_ETC}
      - ${RABBITMQ_CORE_HOST_LOG}:${RABBITMQ_CONTAINER_LOG}
  rabbitmq_wallet:
    container_name: ${RABBITMQ_WALLET_CONTAINER_NAME}
    build:
      context: ${RABBITMQ_HOST_BUILDER_PATH}
      dockerfile: ${DOCKERFILE}
    restart: ${ALWAYS}
    ports:
      - ${RABBITMQ_WALLET_HOST_HTTP_PORT}:${RABBITMQ_CONTAINER_HTTP_PORT}
      - ${RABBITMQ_WALLET_MANAGEMENT_HOST_HTTP_PORT}:${RABBITMQ_MANAGEMENT_CONTAINER_HTTP_PORT}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ${RABBITMQ_WALLET_HOST_ETC}:${RABBITMQ_CONTAINER_ETC}
      - ${RABBITMQ_WALLET_HOST_LOG}:${RABBITMQ_CONTAINER_LOG}
networks:
  mongo_core_network:
  mongo_wallet_network:
volumes:
  mongodbdatacore:
    external: true
  mongodbdatawallet:
    external: true
