parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Infrastructure\:
        resource: '../src/Infrastructure/*'
        exclude: '../src/Infrastructure/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller'
        tags: ['controller.service_arguments']

    App\Infrastructure\Fixtures\AccountFixtures:
        autowire: true
        autoconfigure: true

    App\Application\Command\Transaction\MoneyTransferCommand:
        public: true
        arguments:
            $moneyTransferService: '@App\Domain\Transaction\Service\MoneyTransferService'

    App\Application\Command\UserAccount\CreateCommand:
        public: true
        arguments:
            $createService: '@App\Domain\UserAccount\Service\CreateService'

    App\Application\Command\UserAccount\GetCommand:
        public: true
        arguments:
            $getService: '@App\Domain\UserAccount\Service\GetService'

    App\Application\Command\UserAccount\ListCommand:
        public: true
        arguments:
            $listService: '@App\Domain\UserAccount\Service\ListService'

    App\Application\Command\UserAccount\TransactionOperationListCommand:
        public: true
        arguments:
            $transactionOperationListService: '@App\Domain\UserAccount\Service\TransactionOperationListService'

    App\Domain\Transaction\Service\MoneyTransferService:

    App\Domain\UserAccount\Service\CreateService:
        arguments:
            $accountRepository: '@App\Infrastructure\Domain\UserAccount\Repository\AccountRepository'

    App\Domain\UserAccount\Service\GetService:
        arguments:
            $accountRepository: '@App\Infrastructure\Domain\UserAccount\Repository\AccountRepository'

    App\Domain\UserAccount\Service\ListService:
        arguments:
            $accountRepository: '@App\Infrastructure\Domain\UserAccount\Repository\AccountRepository'

    App\Domain\UserAccount\Service\TransactionOperationListService:
        arguments:
            $accountRepository: '@App\Infrastructure\Domain\UserAccount\Repository\AccountRepository'

    App\Infrastructure\Domain\UserAccount\Repository\AccountRepository:
        arguments:
            $accountRepositoryORM: '@App\Infrastructure\ORM\Repository\AccountRepository'
            $operationRepositoryORM: '@App\Infrastructure\ORM\Repository\OperationRepository'

    App\Infrastructure\ORM\Repository\AccountRepository:
        autowire: true
        public: true

    App\Infrastructure\ORM\Repository\OperationRepository:
        autowire: true
        public: true

    App\Infrastructure\ORM\Repository\TransactionRepository:
        autowire: true
        public: true
