parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Infrastructure\:
        resource: '../src/Infrastructure/*'
        exclude: '../src/Infrastructure/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller'
        tags: ['controller.service_arguments']

    App\Application\Command\UserAccount\CreateCommand:
        public: true
        arguments:
            $createService: '@App\Domain\UserAccount\Service\CreateService'

    App\Domain\UserAccount\Service\CreateService:
        arguments:
            $accountRepository: '@App\Infrastructure\Domain\UserAccount\Repository\AccountRepository'

    App\Infrastructure\Domain\UserAccount\Repository\AccountRepository:
        arguments:
            $accountRepositoryORM: '@App\Infrastructure\ORM\Repository\AccountRepository'

    App\Infrastructure\ORM\Repository\AccountRepository:
        autowire: true
