App\Domain\Entity\UserAccount:
  type: entity
  table: user_accounts
  repositoryClass: App\Infrastructure\ORM\Repository\UserAccountRepository
  fields:
    id:
      type: guid
    password:
      type: string
      length: 255
    createdAt:
      type: datetimetz
    updatedAt:
      type: datetimetz
      nullable: true
  lifecycleCallbacks:
    prePersist: [ setCreatedAtNow ]
    preUpdate: [ setUpdatedAtNow ]
